<SettingsScreen>:
    name: "settings_screen"

    BoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1 
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "Настройки профиля"
            color: 0, 0, 0, 1
            size_hint_y: None
            height: dp(60)
            font_size: "22sp"
            bold: True

        ScrollView:
            BoxLayout:
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                padding: dp(25)
                spacing: dp(20)

                MDTextField:
                    id: name_input
                    hint_text: "Ваше имя"
                    mode: "rectangle"

                MDTextField:
                    id: email_input
                    hint_text: "Email"
                    mode: "rectangle"
                    readonly: True 

                MDTextField:
                    id: pet_name_input
                    hint_text: "Кличка питомца"
                    mode: "rectangle"

                MDRaisedButton:
                    text: "Сохранить изменения"
                    size_hint_x: 1
                    on_release: root.save_profile_firebase()